version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd backend
      - npm ci || npm install
      - cd ..
  build:
    commands:
      - rm -rf dist-index
      - mkdir -p dist-index
      - cp backend/index-photos.js dist-index/index.js
      - cp backend/shared.js dist-index/shared.js
      - cp -R backend/node_modules dist-index/node_modules

artifacts:
  base-directory: dist-index
  files:
    - '**/*'
